name: web_site
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  argo: ^0.0.3
      
  go_router: ^6.0.6

  google_fonts: ^4.0.3

  universal_html: ^2.0.8

  get_it: ^7.2.0

  provider: ^6.0.5
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
